kind: Deployment
apiVersion: apps/v1
metadata:
  name: rngutils
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rngutils
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: rngutils
        deployment: rngutils
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
    spec:
      containers:
        - name: rngutils
          image: registry.xphyrlab.net/rng-tools/rng-tools:latest
          command: ["/sbin/rngd"]
          args: ["-xjitter", "-xhwrng", "-xpkcs11", "-xrtlsdr", "-d", "-f"]
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          imagePullPolicy: Always
          securityContext:
            runAsUser: 0
            capabilities:
              add: ["CAP_SYS_ADMIN"]
      restartPolicy: Always
      terminationGracePeriodSeconds: 30
      dnsPolicy: ClusterFirst
      schedulerName: default-scheduler
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  revisionHistoryLimit: 10
  progressDeadlineSeconds: 600
